name: docker-image
on: [push]

defaults:
  run:
    shell: bash
jobs:
  docker-image:
    name: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run:  sudo apt update && sudo apt install runc containerd docker.io

      - name: rebar3 compile
        run:  scripts/container-build -v -- rebar3 compile

      - name: login to github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/eradio:latest
          push: ${{ github.ref == 'refs/heads/master' }}
